name: build

on: 
  push:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: install packages     
      run: npm ci
    - name: run the tests
      run: npm run test
    - name: build docs and bundle  
      run: npm run build
        
        
